spring.application.name=InventorySystem
#Port
server.port=8080

#DataBase
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=inventory_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Anhvu031025*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# Connection Pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# ===============================
# Security & Auth
# ===============================
jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
jwt.access-token-validity-in-seconds=300000000
jwt.refresh-token-validity-in-seconds=300000000
google.client.id=291635136813-5a7taqf5oqlufen5kc0ee5htb1199shs.apps.googleusercontent.com



# LOGGING
logging.level.com.inventory=DEBUG
logging.level.org.springframework.web=INFO

# FILE UPLOAD
app.upload.dir=uploads
app.upload.max-size=524288000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=100MB